services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "7001:7001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySqlConnection=server=db;database=mothapotheadb;user=root;password=admin
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mothapotheadb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
