// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MothAphotheaShopAPI;

#nullable disable

namespace MothAphotheaShopAPI.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AromaIngredient", b =>
                {
                    b.Property<Guid>("AromasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AromasId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("AromaIngredient");
                });

            modelBuilder.Entity("AromaProduct", b =>
                {
                    b.Property<Guid>("AromasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AromasId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("AromaProduct");
                });

            modelBuilder.Entity("ContraindicationIngredient", b =>
                {
                    b.Property<Guid>("ContraindicationsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ContraindicationsId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("ContraindicationIngredient");
                });

            modelBuilder.Entity("ContraindicationProduct", b =>
                {
                    b.Property<Guid>("ContraindicationsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ContraindicationsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ContraindicationProduct");
                });

            modelBuilder.Entity("EffectIngredient", b =>
                {
                    b.Property<Guid>("EffectsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.HasKey("EffectsId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("EffectIngredient");
                });

            modelBuilder.Entity("EffectProduct", b =>
                {
                    b.Property<Guid>("EffectsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.HasKey("EffectsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("EffectProduct");
                });

            modelBuilder.Entity("FlavorNoteIngredient", b =>
                {
                    b.Property<Guid>("FlavorNotesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.HasKey("FlavorNotesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("FlavorNoteIngredient");
                });

            modelBuilder.Entity("FlavorNoteProduct", b =>
                {
                    b.Property<Guid>("FlavorNotesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.HasKey("FlavorNotesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("FlavorNoteProduct");
                });

            modelBuilder.Entity("IngredientProduct", b =>
                {
                    b.Property<Guid>("IngredientListId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.HasKey("IngredientListId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("IngredientProduct");
                });

            modelBuilder.Entity("IngredientTexture", b =>
                {
                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TexturesId")
                        .HasColumnType("char(36)");

                    b.HasKey("IngredientsId", "TexturesId");

                    b.HasIndex("TexturesId");

                    b.ToTable("IngredientTexture");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Aroma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aromas");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Contraindication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contraindications");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.FlavorNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FlavorNotes");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "scientific_name");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.IngredientType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("IngredientTypes");

                    b.HasAnnotation("Relational:JsonPropertyName", "type");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CaffeineLevel")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "caffeine_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "origin");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "preparation_instructions");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasAnnotation("Relational:JsonPropertyName", "type");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Texture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Textures");
                });

            modelBuilder.Entity("ProductPurchase", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductsId", "PurchaseId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("ProductPurchase");
                });

            modelBuilder.Entity("ProductTexture", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TexturesId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductsId", "TexturesId");

                    b.HasIndex("TexturesId");

                    b.ToTable("ProductTexture");
                });

            modelBuilder.Entity("AromaIngredient", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Aroma", null)
                        .WithMany()
                        .HasForeignKey("AromasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AromaProduct", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Aroma", null)
                        .WithMany()
                        .HasForeignKey("AromasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContraindicationIngredient", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Contraindication", null)
                        .WithMany()
                        .HasForeignKey("ContraindicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContraindicationProduct", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Contraindication", null)
                        .WithMany()
                        .HasForeignKey("ContraindicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EffectIngredient", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EffectProduct", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlavorNoteIngredient", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.FlavorNote", null)
                        .WithMany()
                        .HasForeignKey("FlavorNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlavorNoteProduct", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.FlavorNote", null)
                        .WithMany()
                        .HasForeignKey("FlavorNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientProduct", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientTexture", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Texture", null)
                        .WithMany()
                        .HasForeignKey("TexturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Ingredient", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.IngredientType", "Type")
                        .WithMany("Ingredients")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.Product", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.ProductType", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ProductPurchase", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Purchase", null)
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTexture", b =>
                {
                    b.HasOne("MothAphotheaShopAPI.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MothAphotheaShopAPI.Texture", null)
                        .WithMany()
                        .HasForeignKey("TexturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MothAphotheaShopAPI.IngredientType", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MothAphotheaShopAPI.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
